### ISSUE TITLE
Cannot select button 1 and 2 when configuring double tap behavior in Smart Lighting app

### ISSUE THREAD

**Issue by cnnn** [nuttytree/Nutty-SmartThings#1]
I'm using Smart Lighting app to configure lights. With the GE Z-Wave Plus Switch handler, I am able to select Double Tap button one or two separately, but with GE Z-Wave Plus Dimmer handler, there's no way to select which button.

**Comment by adrian97c** [comment]
What is the ST GitHub intergration info?
