### ISSUE TITLE
Add new switch version

### ISSUE THREAD

**Issue by karrots** [nuttytree/Nutty-SmartThings#2]
The latest GE dimmer switch I received had a newer version string. Please add the below string to the repo for others.

`fingerprint mfr:"0063", prod:"4944", model:"3038", ver: "5.29", deviceJoinName: "GE Z-Wave Plus Wall Dimmer"`

**Comment by adrian97c** [comment]
Is there ST github intergration info?

**Comment by nuttytree** [comment]
Checked in update with new version
